name: gh-pages publisher 🚀

on:
  push:
    branches: [ main ]

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 16
      - run: npm ci
      - run: git config user.name "Daniel Wohlgemuth" && git config user.email "${{secrets.GIT_EMAIL}}"
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
